version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=src/api.py
      - FLASK_ENV=production
      - PYTHONPATH=/app
      # Spotify environment variables will be loaded from .env file
    volumes:
      - ./resources:/app/resources
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    env_file:
      - .env 